# Output path = output_to/output_template
# output_to - This is a parent directory for all of your downloads.
# In case of relative paths, paths are relative to where this module
# was installed.
# Default output path is: <installation path>/downloads
output_to: ./downloads
# This is a template used by youtube_dl.
# The default puts each playlist in it's own folder.
output_template: '%(playlist)s/%(title)s-%(id)s.%(ext)s'
# These are playlists which will be kept.
# Videos that already downloaded won't be downloaded again.
playlists:
#  - your_youtube_playlist_link_here